## Aplicações de funções em colunas

In [7]:
import pandas as pd
import numpy as np

In [8]:
dados = {
    'id_pedido': [1001, 1002, 1003, 1004, 1005],
    'status_cod': [1, 2, 1, 3, np.nan],
    'valor_bruto': [150.50, 2500.00, 45.90, 890.00, np.nan],
    'taxa_juros': [0.05, 0.12, 0.0, 0.10, 0.0],
    'payload_api': [
        '{"plataforma": "app", "versao": "1.2"}', 
        '{"plataforma": "web", "versao": "2.0"}', 
        None, 
        '{"plataforma": "app", "versao": "1.1"}',
        None
    ]
}
print(dados)

df_pedidos = pd.DataFrame(dados)

display(df_pedidos)

{'id_pedido': [1001, 1002, 1003, 1004, 1005], 'status_cod': [1, 2, 1, 3, nan], 'valor_bruto': [150.5, 2500.0, 45.9, 890.0, nan], 'taxa_juros': [0.05, 0.12, 0.0, 0.1, 0.0], 'payload_api': ['{"plataforma": "app", "versao": "1.2"}', '{"plataforma": "web", "versao": "2.0"}', None, '{"plataforma": "app", "versao": "1.1"}', None]}

,id_pedido,status_cod,valor_bruto,taxa_juros,payload_api
0,1001,1.0,150.5,0.05,"{""plataforma"": ""app"", ""versao"": ""1.2""}"
1,1002,2.0,2500.0,0.12,"{""plataforma"": ""web"", ""versao"": ""2.0""}"
2,1003,1.0,45.9,0.00,NaN
3,1004,3.0,890.0,0.10,"{""plataforma"": ""app"", ""versao"": ""1.1""}"
4,1005,NaN,NaN,0.00,NaN

In [9]:
# VETORIZAÇÃO
df_pedidos["valor_com_juros"]= df_pedidos["valor_bruto"] * (1 + df_pedidos["taxa_juros"])

display(df_pedidos)

,id_pedido,status_cod,valor_bruto,taxa_juros,payload_api,valor_com_juros
0,1001,1.0,150.5,0.05,"{""plataforma"": ""app"", ""versao"": ""1.2""}",158.025
1,1002,2.0,2500.0,0.12,"{""plataforma"": ""web"", ""versao"": ""2.0""}",2800.000
2,1003,1.0,45.9,0.00,NaN,45.900
3,1004,3.0,890.0,0.10,"{""plataforma"": ""app"", ""versao"": ""1.1""}",979.000
4,1005,NaN,NaN,0.00,NaN,NaN

In [10]:
# Método APLY
### criando função a ser aplicada
def calcular_frete(valor, tarifa_base, multiplicador_de_risco):
    # para valores nulos ou não numericos
    if pd.isna(valor):
        return np.nan
    valor_frete = 0.0 if valor > 100 else tarifa_base*multiplicador_de_risco
    return valor_frete

# aplicar no dataframe
df_pedidos["frete"] = df_pedidos['valor_bruto'].apply(calcular_frete,args=(15.0,1.2))

display(df_pedidos)

,id_pedido,status_cod,valor_bruto,taxa_juros,payload_api,valor_com_juros,frete
0,1001,1.0,150.5,0.05,"{""plataforma"": ""app"", ""versao"": ""1.2""}",158.025,0.0
1,1002,2.0,2500.0,0.12,"{""plataforma"": ""web"", ""versao"": ""2.0""}",2800.000,0.0
2,1003,1.0,45.9,0.00,NaN,45.900,18.0
3,1004,3.0,890.0,0.10,"{""plataforma"": ""app"", ""versao"": ""1.1""}",979.000,0.0
4,1005,NaN,NaN,0.00,NaN,NaN,NaN

In [11]:
# MAP (substitui)
dicionario_status= {
    1:"Aguardando Pagamento",
    2:"Pagamento Aprovado",
    3:"Enviado"
}
df_pedidos["status"] = df_pedidos['status_cod'].map(dicionario_status, na_action='ignore')
display(df_pedidos)

,id_pedido,status_cod,valor_bruto,taxa_juros,payload_api,valor_com_juros,frete,status
0,1001,1.0,150.5,0.05,"{""plataforma"": ""app"", ""versao"": ""1.2""}",158.025,0.0,Aguardando Pagamento
1,1002,2.0,2500.0,0.12,"{""plataforma"": ""web"", ""versao"": ""2.0""}",2800.000,0.0,Pagamento Aprovado
2,1003,1.0,45.9,0.00,NaN,45.900,18.0,Aguardando Pagamento
3,1004,3.0,890.0,0.10,"{""plataforma"": ""app"", ""versao"": ""1.1""}",979.000,0.0,Enviado
4,1005,NaN,NaN,0.00,NaN,NaN,NaN,NaN

## Condicionais

In [12]:
dados_credito = {
    'id_cliente': [101, 102, 103, 104, 105],
    'dias_atraso': [0, 15, 45, 90, 5],
    'valor_divida': [0.0, 150.0, 890.5, 3500.0, 45.0],
    'score_credito': [850, 600, 450, 300, 720],
    'plano_assinatura': ['Premium', 'Básico', 'Básico', 'Premium', 'Básico']
}

df_creditos = pd.DataFrame(dados_credito)

display(df_creditos)

   id_cliente  dias_atraso  valor_divida  score_credito plano_assinatura
0         101            0           0.0            850          Premium
1         102           15         150.0            600           Básico
2         103           45         890.5            450           Básico
3         104           90        3500.0            300          Premium
4         105            5          45.0            720           Básico

In [15]:
# np.where()

df_creditos["multa_aplicada"]= np.where(
    df_creditos['dias_atraso']>0, # condição
    20.0+ (df_creditos['dias_atraso']*0.02), # se verdadeiro
    0.0 # se falsa
)

display(df_creditos)

# np.select
## LISTA DE  Condições
condocoes= [
    df_creditos['dias_atraso'] == 0,
    df_creditos['dias_atraso'] <= 15,
    df_creditos['dias_atraso'] <= 60,
    df_creditos['dias_atraso'] > 60,
]

resultados = [
    'Em dias',
    'Lembrete',
    'Cobrança',
    'Juridico'
]

# aplicar select
df_creditos['acao'] = np.select(condocoes,resultados, default="Analizar manualmente")

display(df_creditos)

# LOC
filtro= df_creditos['dias_atraso'] > 60

#aplicar loc
df_creditos.loc[filtro,['plano_assinatura','score_credito']]=['Cancelado',0]
display(df_creditos)

,id_cliente,dias_atraso,valor_divida,score_credito,plano_assinatura,multa_aplicada,acao
0,101,0,0.0,850,Premium,0.0,Em dias
1,102,15,150.0,600,Básico,20.3,Lembrete
2,103,45,890.5,450,Básico,20.9,Cobrança
3,104,90,3500.0,300,Premium,21.8,Juridico
4,105,5,45.0,720,Básico,20.1,Lembrete

,id_cliente,dias_atraso,valor_divida,score_credito,plano_assinatura,multa_aplicada,acao
0,101,0,0.0,850,Premium,0.0,Em dias
1,102,15,150.0,600,Básico,20.3,Lembrete
2,103,45,890.5,450,Básico,20.9,Cobrança
3,104,90,3500.0,300,Premium,21.8,Juridico
4,105,5,45.0,720,Básico,20.1,Lembrete

,id_cliente,dias_atraso,valor_divida,score_credito,plano_assinatura,multa_aplicada,acao
0,101,0,0.0,850,Premium,0.0,Em dias
1,102,15,150.0,600,Básico,20.3,Lembrete
2,103,45,890.5,450,Básico,20.9,Cobrança
3,104,90,3500.0,0,Cancelado,21.8,Juridico
4,105,5,45.0,720,Básico,20.1,Lembrete

In [18]:
#Mask
dados_sensor = {
    'id_leitura': [1, 2, 3, 4, 5],
    'temperatura': [45.0, 52.5, 999.0, 48.0, -50.0] # 999 e -50 são anomalias
}
df_sensores = pd.DataFrame(dados_sensor)
display(df_sensores)

cond_valid= (df_sensores['temperatura']>=0) & (df_sensores['temperatura'] <=100)
df_sensores['tep_limpo']= df_sensores['temperatura'].where(cond_valid, np.nan)
display(df_sensores)

   id_leitura  temperatura
0           1         45.0
1           2         52.5
2           3        999.0
3           4         48.0
4           5        -50.0

   id_leitura  temperatura  tep_limpo
0           1         45.0       45.0
1           2         52.5       52.5
2           3        999.0        NaN
3           4         48.0       48.0
4           5        -50.0        NaN

In [ ]:
## Junção

In [20]:
# Datasets de Exemplo: Varejo
vendas_janeiro = pd.DataFrame({'id_pedido': [1001, 1002], 'cod_produto': ['A1', 'B2'], 'qtde': [2, 1]})
vendas_fevereiro = pd.DataFrame({'id_pedido': [1003, 1004, 1005], 'cod_produto': ['A1', 'C3', 'X9'], 'qtde': [5, 2, 1]})
cadastro_produtos = pd.DataFrame({'codigo': ['A1', 'B2', 'C3'], 'nome_produto': ['Notebook', 'Mouse', 'Teclado']})

# ==============================================================================
# 1. PD.CONCAT (Empilhamento Estrutural)
# ==============================================================================
df_vendas_totais = pd.concat(
    [vendas_janeiro, vendas_fevereiro], 
    keys=['Jan', 'Fev']
).reset_index(level=0).rename(columns={'level_0': 'mes_origem'})

display(vendas_janeiro)
display(vendas_fevereiro)
display(df_vendas_totais)

# ==============================================================================
# 2. PD.MERGE (Cruzamento Relacional tipo JOIN)
# ==============================================================================
# PARÂMETROS IMPORTANTES:
# - how='left': Garante que não perderemos nenhuma venda da tabela da esquerda.
# - left_on / right_on: Necessário porque a coluna chave tem nomes diferentes nas tabelas.
# - indicator=True: Adiciona a coluna '_merge' vital para auditar cruzamentos vazados.
df_enriquecido = pd.merge(
    left=df_vendas_totais, 
    right=cadastro_produtos, 
    how='left', 
    left_on='cod_produto', 
    right_on='codigo', 
    indicator=True
)

display(df_enriquecido)

# Isolando o produto vendido que não tem cadastro na base de dados (o produto 'X9')
# O how='left' salvou ele de ser excluído, e o indicator nos permite achá-lo facilmente.
erros_cadastro = df_enriquecido[df_enriquecido['_merge'] == 'left_only']

   id_pedido cod_produto  qtde
0       1001          A1     2
1       1002          B2     1

   id_pedido cod_produto  qtde
0       1003          A1     5
1       1004          C3     2
2       1005          X9     1

  mes_origem  id_pedido cod_produto  qtde
0        Jan       1001          A1     2
1        Jan       1002          B2     1
0        Fev       1003          A1     5
1        Fev       1004          C3     2
2        Fev       1005          X9     1

  mes_origem  id_pedido cod_produto  qtde codigo nome_produto     _merge
0        Jan       1001          A1     2     A1     Notebook       both
1        Jan       1002          B2     1     B2        Mouse       both
2        Fev       1003          A1     5     A1     Notebook       both
3        Fev       1004          C3     2     C3      Teclado       both
4        Fev       1005          X9     1    NaN          NaN  left_only